### ISSUE TITLE
Problem with custom scrollbars on some websites

### ISSUE THREAD

**Issue by Keith94** [Ri100/PrimeBars#1]
Certain websites like Twitch and Soundcloud have their own custom scrollbar style, which conflicts with OverlayScrollbar's style.

For example on any Twitch channels (such as [Bananasaurus_Rex](https://www.twitch.tv/bananasaurus_rex/videos/all)) when hovering the scrollbar, both styles get applied at once and looks quite buggy.

![firefox_2016-10-24_14-20-55](https://cloud.githubusercontent.com/assets/5490615/19664479/65499594-99f5-11e6-877c-d092c7dfdec8.png)

And on Soundcloud, go to https://soundcloud.com/griz and click the "View 13 tracks" and hover the scrollbar, which has the same problem.

![firefox_2016-10-24_14-18-59](https://cloud.githubusercontent.com/assets/5490615/19664549/cb4a0b80-99f5-11e6-81ba-2bcdd196b7ee.png)

Can something be done to fix it maybe? That's mainly why I disabled the add-on until there's a fix.

**Comment by Keith94** [comment]
Also, Discord servers on discordapp.com have the same issue..

![firefox_2016-10-24_14-37-25](https://cloud.githubusercontent.com/assets/5490615/19664925/86685e70-99f7-11e6-9b75-f7d6e40cc0f6.png)

**Comment by Keith94** [comment]
Problems with Twitch and SoundCloud can be "solved" by adding CSS...

```css
@-moz-document domain("www.twitch.tv") {
  .tse-scrollbar {
    opacity: 0 !important;
  }
}
@-moz-document domain("soundcloud.com") {
  .g-scrollbar.g-scrollbar-vertical.g-scrollbar-visible {
    opacity: 0 !important;
  }
}
```
